name: "Flexlate Update and PR"
description: "Run Flexlate update and create a PR or issue"
inputs:
  gh_token: # id of input
    description: "Github Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Flexlate
      run: pip install flexlate
      shell: bash
    - name: Set Git Committer
      run: |
        git config --global user.email "flexlate@nickderobertis.com"
        git config --global user.name "Flexlate"
      shell: bash
    - name: Check if template is out of date
      id: template_check
      run: |
        if ! fxt check; then
          echo "Need to update template. Will do so and open PR.";
          echo ::set-output name=template_update::true;
        else
          echo "No updates to template needed, will exit workflow.";
          echo ::set-output name=template_update::false;
        fi;
      shell: bash
    - name: Set template update branch
      if: steps.template_check.outputs.template_update == 'true'
      run: git checkout -b template-patches
      shell: bash
    - name: Template Update
      id: template_update
      if: steps.template_check.outputs.template_update == 'true'
      run: |
        # Temporarily assume conflict state and force exit
        fxt update --no-input &
        FLEXLATE_PID=$!
        sleep 10
        kill $FLEXLATE_PID
        git merge --abort
        echo ::set-output name=update_has_conflicts::false;
        # if fxt update --no-input --abort; then
        #   echo "Applied updates successfully.";
        #   echo ::set-output name=update_has_conflicts::false;
        # else
        #   echo "Encountered conflicts while trying to apply update. Will open an issue rather than a PR.";
        #   echo ::set-output name=update_has_conflicts::true;
        # fi;
      shell: bash
    - name: Create Issue to Manually Update Template
      if: steps.template_check.outputs.template_update == 'true' && steps.template_update.outputs.update_has_conflicts == 'true'
      uses: JasonEtco/create-an-issue@5ee5d5edcd3777b7d5482d9342d3f08cd8daa3cd
      with:
        filename: temp-issue-template.md
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
    - name: Push changes to Flexlate template branch
      if: steps.template_check.outputs.template_update == 'true'
      run: git push origin flexlate-templates-template-patches
      shell: bash
    - name: Push changes to Flexlate output branch
      if: steps.template_check.outputs.template_update == 'true'
      run: git push origin flexlate-output-template-patches
      shell: bash
    - name: Set back to main branch
      if: steps.template_check.outputs.template_update == 'true'
      run: |
        git checkout "$CHECKOUT_BRANCH"
        git merge template-patches
      env:
        CHECKOUT_BRANCH: ${{ github.ref_name }}
      shell: bash
    - name: Create Direct PR with template update
      if: steps.template_check.outputs.template_update == 'true' && steps.template_update.outputs.update_has_conflicts == 'false'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.gh_token }}
        commit-message: Update project template using Flexlate
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: "Update project template using Flexlate"
        body: |
          Update template using Flexlate.

          Before merging, review the changes and adjust manually if necessary.

          - Updates coming from [copier-pypi-sphinx-flexlate][1]

          [1]: https://github.com/nickderobertis/copier-pypi-sphinx-flexlate
        labels: no auto merge, automated pr
        branch: template-patches
    - name: Create PR For Resolving Merge Conflicts
      if: steps.template_check.outputs.template_update == 'true' && steps.template_update.outputs.update_has_conflicts == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.gh_token }}
        commit-message: Update project template using Flexlate
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: "Update project template using Flexlate"
        body: |
          Update template using Flexlate.

          Before merging, review the changes and adjust manually if necessary.

          - Updates coming from [copier-pypi-sphinx-flexlate][1]

          [1]: https://github.com/nickderobertis/copier-pypi-sphinx-flexlate
        labels: no auto merge, automated pr
        branch: flexlate-templates-template-patches
        base: flexlate-output-template-patches
